# Generated by Django 4.0.4 on 2022-05-09 22:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Secteur',
            fields=[
                ('id_secteur', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('wilaya_secteur', models.CharField(max_length=15)),
                ('sec_color', models.CharField(max_length=15)),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
