# Generated by Django 4.0.4 on 2022-05-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_secteur',
            old_name='name',
            new_name='sec_name',
        ),
    ]
