# Generated by Django 4.0.4 on 2022-05-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_rename_name_tbl_secteur_sec_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_secteur',
            name='sec_creator',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tbl_secteur',
            name='sec_color',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tbl_secteur',
            name='sec_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='tbl_secteur',
            name='wilaya_secteur',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
