# Generated by Django 4.0.4 on 2022-05-13 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_tbl_secteur_sec_creator_alter_tbl_secteur_sec_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_secteur',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
