# Generated by Django 4.0.4 on 2022-05-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_tbl_secteur_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_secteur',
            name='is_deleted',
            field=models.IntegerField(default=0),
        ),
    ]
