# Generated by Django 4.0.4 on 2022-05-13 12:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_tbl_secteur_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_secteur',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326),
        ),
    ]
