# Generated by Django 4.0.4 on 2022-05-20 10:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0006_alter_tbl_secteur_poly'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Wilaya',
            fields=[
                ('id_city', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=15)),
                ('city_code', models.IntegerField(blank=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326)),
            ],
        ),
    ]
