# Generated by Django 4.0.4 on 2022-05-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_tbl_wilaya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_wilaya',
            name='city_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
